server:
  port: 8081
spring:
  application:
    name: service-product
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://101.200.88.43:3306/shop?serverTimezone=Asia/Shanghai&characterEncoding=utf8&useSSL=false
    username: admin
    password: 1234qwer,
  jpa:
    properties:
      hibernate:
        hbm2ddl:
          auto: update
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
  cloud:
    nacos:
      discovery:
        server-addr: 101.200.88.43:8848