server:
  port: 8071
spring:
  application:
    name: service-user
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://101.200.88.43:3306/shop?serverTimezone=Asia/Shanghai&characterEncoding=utf8&useSSL=true
    username: admin
    password: 1234qwer,
  jpa:
    properties:
      hibernate:
        hbm2ddl:
          auto: update
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect